name: StreamCaster CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: alpine-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd app
          pip install -r requirements.txt
          pip install flake8 black

      - name: Run Flake8
        run: |
          cd app
          flake8 .

      - name: Run Black
        run: |
          cd app
          black --check .

      - name: Run tests
        run: |
          cd app
          # Replace this with your test command
          pytest tests/

  docker:
    runs-on: alpine-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME={{ secrets.DOCKERHUB_USERNAME }}/{{ secrets.DOCKERHUB_IMAGENAME }}
          TAG=latest
          VERSION=${{ github.run_number }} # Alternative: use a versioning strategy
          
          # Build the Docker image
          docker build -t $IMAGE_NAME:$TAG .

          # Tag with version
          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:$VERSION

          # Push both tags to Docker Hub
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:$VERSION
  
  publish:
    runs-on: alpine-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create a new branch
        run: |
          git config --global user.name "${{ secrets.GITHUB_USERNAME }}"
          git config --global user.email "${{ secrets.GITHUB_EMAIL }}"
          git checkout -b release-${{ github.run_number }}

      - name: Commit and Push changes
        run: |
          git add .
          git commit -m "Automated release"
          git push origin release-${{ github.run_number }}

      - name: Merge to master
        run: |
          git checkout master
          git merge release-${{ github.run_number }}
          git push origin master
